"""empty message

Revision ID: 3608d941ad44
Revises: 
Create Date: 2018-09-11 10:22:38.739874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3608d941ad44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actual_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datatime', sa.String(length=100), nullable=False),
    sa.Column('data_list', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('last_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=15), nullable=False),
    sa.Column('data_list', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_data')
    op.drop_table('actual_data')
    # ### end Alembic commands ###
